package org.installer;

import java.awt.CardLayout;

/**
 * AppMain is the startup class of the applet.
 * It will create a CardLayout and manage card switching and data passing.
 * There are 2 cards: InstallSettings and Installation.
 * 
 * @author sajty
 */
public class AppMain extends javax.swing.JApplet {

    /** Initializes the applet AppMain */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //set app for inline classes. 
        mApp = this;
        
        //initialize variables.

        
        /* Create and display the applet */
        try {
            
            //wait for the window to set up, before inserting GUI elements.
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                @Override
                public void run() {
                    
                    //This class contains a CardLayout, where only the top card is visible.
                    //Initialize GUI components autogenerated by netbeans.
                    initComponents();
                    
                    //add 2 cards to the stack.
                    mInstallSettings = new org.installer.InstallSettings(mApp);
                    mInstallation = new org.installer.Installation(mApp);
                    getContentPane().add(mInstallSettings, "cardSettings");
                    getContentPane().add(mInstallation, "cardInstall");
                    CardLayout cl = (CardLayout)(getContentPane().getLayout());
                    
                    //set it to the first card. (installSettings)
                    cl.first(getContentPane());
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * Switch to the install card and start installing
     * 
     * @param _osType Operating System type. It can be 0(Linux 32 bit),
     * 1(Linux 64bit), 2(Windows), 3(Mac OS X).
     * @param path The installation path. On Mac OS X this is not needed.
     */
    public void startInstall( int osType, String path){
        //switch to next card. (installation)
        CardLayout cl = (CardLayout)(getContentPane().getLayout());
        cl.next(getContentPane());
        
        //start installation process.
        mInstallation.runInstall(osType, path);
    }
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Same as this objects. This is needed for inline classes, where "this" is different.  
     */
    private AppMain mApp;

    /**
     * InstallSettings card.
     */
    private InstallSettings mInstallSettings;

    /**
     * Installation card.
     */
    private Installation mInstallation;

}
