package org.installer;


import com.sun.servicetag.Installer;
import java.awt.CardLayout;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AppMain.java
 *
 * Created on 2011.08.12., 8:47:10
 */
/**
 *
 * @author sajty
 */
public class AppMain extends javax.swing.JApplet {

    /** Initializes the applet AppMain */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         app = this;
         osType = 0;
         installPath = "";
        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {

                public void run() {
                    initComponents();
                    
                    installSettings = new org.installer.InstallSettings(app);
                    installation = new org.installer.Installation(app);
                    getContentPane().add(installSettings, "cardSettings");
                    getContentPane().add(installation, "cardInstall");
                    CardLayout cl = (CardLayout)(getContentPane().getLayout());
                    cl.first(getContentPane());
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    public void startInstall( int osType, String path){
        CardLayout cl = (CardLayout)(getContentPane().getLayout());
        cl.next(getContentPane());
    }
    public int getOS() {
        return osType;
    }
    public String getIntallPath() {
        return installPath;
    }
    public void completeInstall(boolean success){
        
    }
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private AppMain app;
    private org.installer.InstallSettings installSettings;
    private org.installer.Installation installation;
    private int osType;
    private String installPath;

}
