package org.installer;

import javax.swing.JFileChooser;

/**
 * Installation settings dialog.
 * 
 * @author sajty
 */
public class InstallSettings extends javax.swing.JPanel {

    /** Creates new form InstallSettings */
    public InstallSettings(org.installer.AppMain _app) {
        mApp = _app;
        
        //Initialize GUI components autogenerated by netbeans.
        initComponents();
        
        //Set OS default values at startup.
        AutoDetectOS();
        cmbOSItemStateChanged(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        btnAutoDetect = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnInstall = new javax.swing.JButton();
        txtInstallPath = new javax.swing.JTextField();
        cmbOS = new javax.swing.JComboBox();
        lblDir = new javax.swing.JLabel();
        lblOS = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setPreferredSize(new java.awt.Dimension(400, 300));

        btnBrowse.setText("...");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        btnAutoDetect.setText("auto-detect");
        btnAutoDetect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoDetectActionPerformed(evt);
            }
        });

        lblWelcome.setText("Welcome to the webember installer");

        btnInstall.setText("Install");
        btnInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallActionPerformed(evt);
            }
        });

        txtInstallPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstallPathActionPerformed(evt);
            }
        });

        cmbOS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Linux (32 bit)", "Linux (64 bit)", "Windows", "Mac OS X" }));
        cmbOS.setName(""); // NOI18N
        cmbOS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOSItemStateChanged(evt);
            }
        });
        cmbOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOSActionPerformed(evt);
            }
        });

        lblDir.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDir.setText("Installation directory:");

        lblOS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOS.setText("Your OS:");

        jLabel2.setText("Please check the OS and install dir, then click on Install.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(btnInstall, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(384, 384, 384))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtInstallPath, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbOS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAutoDetect))
                .addContainerGap(250, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(345, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOS)
                    .addComponent(btnAutoDetect))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInstallPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDir)
                    .addComponent(btnBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50)
                .addComponent(btnInstall, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
    }// </editor-fold>//GEN-END:initComponents

private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
    
    JFileChooser chooser = new JFileChooser(); 
    chooser.setDialogTitle("Choose directory...");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    
    //disable the "All files" option.
    chooser.setAcceptAllFileFilterUsed(false);
    
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        txtInstallPath.setText(chooser.getSelectedFile().toString());
    }
}//GEN-LAST:event_btnBrowseActionPerformed

private void btnAutoDetectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoDetectActionPerformed
    AutoDetectOS();
}//GEN-LAST:event_btnAutoDetectActionPerformed
/**
 * Detects OS and sets the gui elements to the default OS value.
 * NOTE: this will invoke CmbOSItemStateChanged
 */
private void AutoDetectOS() {
    int osType;
    String osName = System.getProperty("os.name").toLowerCase();
    //Get java VM architecture! It may not be the same as the OS.
    String osArch = System.getProperty("os.arch");
    if(osName.contains("win")){
        osType = 2;//Windows
    } else if(osName.contains("mac")){
        osType = 3;//Mac OS X
    } else if(osArch.contains("64")) {
        osType = 1;//Linux 64 bit
    } else {
        osType = 0;//Linux 32 bit
    }
    //change combobox, it will invoke CmbOSItemStateChanged function.
    cmbOS.setSelectedIndex(osType);
    
}
private void btnInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallActionPerformed
    mApp.startInstall(cmbOS.getSelectedIndex(), txtInstallPath.getText());
}//GEN-LAST:event_btnInstallActionPerformed

private void txtInstallPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstallPathActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtInstallPathActionPerformed

private void cmbOSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOSItemStateChanged
    //get the new item index.
    int osType = cmbOS.getSelectedIndex();
    //set default install path.
    txtInstallPath.setText(mPathDefault[osType]);
    //hide install path, if its Mac OS X.
    txtInstallPath.setVisible(mPathEnabled[osType]);
    //hide label too.
    lblDir.setVisible(mPathEnabled[osType]);
    //hide browse button too.
    btnBrowse.setVisible(mPathEnabled[osType]);
}//GEN-LAST:event_cmbOSItemStateChanged

private void cmbOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOSActionPerformed

}//GEN-LAST:event_cmbOSActionPerformed
    
    /**
     * Lookup table for default install paths.
     */
    private final String mPathDefault[] = {"~/opt/webember", "~/opt/webember", "C:\\Program Files\\webember", null};
    /**
     * Lookup table for Path visibility.
     */
    private final boolean mPathEnabled[] = {true, true, true, false};
    /**
     * reference app main object passed by the constructor.
     */
    private final AppMain mApp;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutoDetect;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnInstall;
    private javax.swing.JComboBox cmbOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblOS;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtInstallPath;
    // End of variables declaration//GEN-END:variables
}
