package org.installer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InstallSettings.java
 *
 * Created on 2011.08.12., 9:05:52
 */
/**
 *
 * @author sajty
 */

import javax.swing.JFileChooser;
        
public class InstallSettings extends javax.swing.JPanel {

    /** Creates new form InstallSettings */
    public InstallSettings(org.installer.AppMain _app) {
        app = _app;
        initComponents();
        AutoDetectOS();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnBrowse = new javax.swing.JButton();
        BtnAutoDetect = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnInstall = new javax.swing.JButton();
        txtInstallPath = new javax.swing.JTextField();
        CmbOS = new javax.swing.JComboBox();
        lblDir = new javax.swing.JLabel();
        lblOS = new javax.swing.JLabel();

        BtnBrowse.setText("...");
        BtnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBrowseActionPerformed(evt);
            }
        });

        BtnAutoDetect.setText("auto-detect");
        BtnAutoDetect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAutoDetectActionPerformed(evt);
            }
        });

        lblWelcome.setText("Welcome to the webember installer.");

        btnInstall.setText("Install");
        btnInstall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstallActionPerformed(evt);
            }
        });

        txtInstallPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInstallPathActionPerformed(evt);
            }
        });

        CmbOS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Linux", "Windows", "Mac OS X" }));
        CmbOS.setName(""); // NOI18N
        CmbOS.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CmbOSItemStateChanged(evt);
            }
        });
        CmbOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbOSActionPerformed(evt);
            }
        });

        lblDir.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDir.setText("Installation directory:");

        lblOS.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblOS.setText("Your OS:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblOS, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblDir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(CmbOS, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(BtnAutoDetect))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtInstallPath, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(BtnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(lblWelcome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnInstall)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 315, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CmbOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAutoDetect)
                    .addComponent(lblOS))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInstallPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBrowse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDir))
                .addGap(18, 18, 18)
                .addComponent(btnInstall)
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

private void BtnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBrowseActionPerformed
    JFileChooser chooser = new JFileChooser(); 
    chooser.setDialogTitle("Choose directory...");
    chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
    //
    // disable the "All files" option.
    //
    chooser.setAcceptAllFileFilterUsed(false);
    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        txtInstallPath.setText(chooser.getSelectedFile().toString());
    }
}//GEN-LAST:event_BtnBrowseActionPerformed

private void BtnAutoDetectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAutoDetectActionPerformed
    AutoDetectOS();
}//GEN-LAST:event_BtnAutoDetectActionPerformed
private void AutoDetectOS() {
    int osType;
    String osName = System.getProperty("os.name").toLowerCase();
    if(osName.contains("win")){
        osType = 1;
    } else if(osName.contains("mac")){
        osType = 2;
    } else {
        osType = 0;
    }
    CmbOS.setSelectedIndex(osType);
    
}
private void btnInstallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstallActionPerformed
    app.startInstall(CmbOS.getSelectedIndex(), txtInstallPath.getText());
}//GEN-LAST:event_btnInstallActionPerformed

private void txtInstallPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInstallPathActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_txtInstallPathActionPerformed

private void CmbOSItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CmbOSItemStateChanged
    int osType = CmbOS.getSelectedIndex();
    txtInstallPath.setText(PathDefault[osType]);
    lblDir.setVisible(PathEnabled[osType]);
    txtInstallPath.setVisible(PathEnabled[osType]);
    BtnBrowse.setVisible(PathEnabled[osType]);
}//GEN-LAST:event_CmbOSItemStateChanged

private void CmbOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbOSActionPerformed

}//GEN-LAST:event_CmbOSActionPerformed
    
    private final String PathDefault[] = {"~/opt/webember", "c:\\Program Files\\webember", null};
    private final boolean PathEnabled[] = {true, true, false};
    private final AppMain app;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAutoDetect;
    private javax.swing.JButton BtnBrowse;
    private javax.swing.JComboBox CmbOS;
    private javax.swing.JButton btnInstall;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblOS;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtInstallPath;
    // End of variables declaration//GEN-END:variables
}
